name: Cypress Single Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


      - name: Run ONLY one Cypress test file
        run: npx cypress run --spec "cypress/e2e/functionaltests.cy.js"
